apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: rentzone-secret
  namespace: rentzone
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:<region>:<account-id>:secret:rentzone-secret-<random-key>"
          objectAlias: "app-secret"